"""Live network connections, per application.

Answers a different question from the rest of NetVitals: not *how much* has
moved, but *what is talking to what, right now*. It needs no elevation — the
connection table for processes running as you is readable by you — so unlike
the per-application byte counts this works in the Microsoft Store build.

Each connection is also labelled with which side of the VPN it is on, by
matching its local address against the addresses held by tunnel adapters. That
is the same judgement the totals depend on, shown per connection.

No name resolution is performed. Turning addresses into hostnames would mean a
DNS lookup per remote host, which is outbound traffic generated by the very
tool that claims to make only one outbound request.
"""
from __future__ import annotations

import time

from .net_system import DIRECT, VPN, classify_adapter

try:
    import psutil
except ImportError:  # pragma: no cover
    psutil = None

#: How long a process name is cached. Names never change for a live PID, and
#: looking one up costs a handle open per connection otherwise.
NAME_TTL = 30.0

#: How often the set of tunnel-owned local addresses is rebuilt.
TUNNEL_TTL = 10.0

#: Connection states worth showing by default. A listening socket is not a
#: conversation, and the page is about conversations.
ACTIVE_STATES = ("ESTABLISHED", "SYN_SENT", "SYN_RECV", "CLOSE_WAIT",
                 "FIN_WAIT1", "FIN_WAIT2", "LAST_ACK", "CLOSING", "NONE")


class ConnectionCollector:
    """Reads the system connection table on demand."""

    def __init__(self) -> None:
        self._names: dict[int, tuple[str, float]] = {}
        self._tunnel_ips: set[str] = set()
        self._tunnel_ts = 0.0
        #: Connections the operating system would not let us attribute. Shown
        #: rather than hidden: a count that silently excludes what it could not
        #: read is a lie of omission.
        self.unreadable = 0

    # ------------------------------------------------------------------
    def _refresh_tunnels(self, force: bool = False) -> None:
        if psutil is None:
            return
        now = time.time()
        if not force and now - self._tunnel_ts < TUNNEL_TTL:
            return
        self._tunnel_ts = now
        try:
            found: set[str] = set()
            for name, entries in psutil.net_if_addrs().items():
                if classify_adapter(name) != VPN:
                    continue
                for entry in entries:
                    if entry.address:
                        found.add(entry.address.split("%")[0])
            self._tunnel_ips = found
        except Exception:
            pass

    def _name_for(self, pid: int | None) -> str:
        if not pid:
            return "System"
        now = time.time()
        cached = self._names.get(pid)
        if cached and now - cached[1] < NAME_TTL:
            return cached[0]
        try:
            name = psutil.Process(pid).name()
        except Exception:
            # Access denied, or it exited between listing and asking.
            name = f"PID {pid}"
        self._names[pid] = (name, now)
        return name

    # ------------------------------------------------------------------
    def snapshot(self, include_listening: bool = False) -> list[dict]:
        """Every active connection, newest information first.

        Sorted by application then remote address, so the same program's
        conversations sit together rather than scattering as ports change.
        """
        if psutil is None:
            return []
        self._refresh_tunnels()
        self.unreadable = 0

        try:
            entries = psutil.net_connections(kind="inet")
        except Exception:
            # On Windows some connections belong to processes we may not
            # query; psutil raises rather than returning a partial list.
            self.unreadable = -1
            return []

        rows: list[dict] = []
        for conn in entries:
            status = conn.status or "NONE"
            if not include_listening and status not in ACTIVE_STATES:
                continue
            if not conn.raddr and not include_listening:
                continue

            local_ip = getattr(conn.laddr, "ip", "") or ""
            rows.append({
                "app": self._name_for(conn.pid),
                "pid": conn.pid or 0,
                "protocol": "TCP" if conn.type.name == "SOCK_STREAM" else "UDP",
                "local_port": getattr(conn.laddr, "port", 0) or 0,
                "remote_ip": getattr(conn.raddr, "ip", "") or "",
                "remote_port": getattr(conn.raddr, "port", 0) or 0,
                "status": status,
                "link": VPN if local_ip in self._tunnel_ips else DIRECT,
            })

        rows.sort(key=lambda r: (r["app"].lower(), r["remote_ip"],
                                 r["remote_port"]))
        return rows

    def grouped(self, rows: list[dict]) -> list[dict]:
        """Collapse repeated conversations into one row with a count.

        A browser holds dozens of connections to the same host on the same
        port; listing each separately fills the page with identical lines and
        buries everything else. What a person wants to know is who is talking
        to whom, and how much of it there is.
        """
        groups: dict[tuple, dict] = {}
        for row in rows:
            key = (row["app"], row["protocol"], row["remote_ip"],
                   row["remote_port"], row["link"])
            entry = groups.get(key)
            if entry is None:
                entry = groups[key] = {
                    "app": row["app"], "pid": row["pid"],
                    "protocol": row["protocol"], "remote_ip": row["remote_ip"],
                    "remote_port": row["remote_port"], "link": row["link"],
                    "count": 0, "states": {},
                }
            entry["count"] += 1
            entry["states"][row["status"]] = entry["states"].get(row["status"], 0) + 1

        out = []
        for entry in groups.values():
            # The most common state, so a single closing socket does not
            # relabel an otherwise established conversation.
            entry["status"] = max(entry["states"].items(), key=lambda kv: kv[1])[0]
            del entry["states"]
            out.append(entry)
        out.sort(key=lambda e: (-e["count"], e["app"].lower(), e["remote_ip"]))
        return out

    def summary(self, rows: list[dict]) -> list[dict]:
        """One line per application: how many connections, and where.

        The full table is long and repetitive — a browser alone holds dozens.
        This is what the dashboard shows.
        """
        by_app: dict[str, dict] = {}
        for row in rows:
            entry = by_app.setdefault(row["app"], {
                "app": row["app"], "connections": 0,
                "hosts": set(), "tunnelled": 0})
            entry["connections"] += 1
            if row["remote_ip"]:
                entry["hosts"].add(row["remote_ip"])
            if row["link"] == VPN:
                entry["tunnelled"] += 1

        out = []
        for entry in by_app.values():
            entry["hosts"] = len(entry["hosts"])
            out.append(entry)
        out.sort(key=lambda e: (-e["connections"], e["app"].lower()))
        return out
